### ISSUE TITLE
Not launching any programs on SteamVR launch

### ISSUE THREAD

**Issue by EchoTheNeko** [dreiekk/OpenVR-Autostarter#12]
SteamVR beta 2.5.2
OpenVR-Autostarter 0.4.0

Nothing happens whens starting SteamVR, i assume something is supposed to appear in the "Choose Startup Overlay Apps" in SteamVR but just nothing happens or shows.

**Comment by dreiekk** [comment]
Hi @EchoTheNeko,

that's right, "OpenVR-Autostarter" should be listed in the "Choose Startup Overlay Apps" settings window in SteamVR.

![grafik](https://github.com/dreiekk/OpenVR-Autostarter/assets/25348281/d8565675-e2de-4bea-8c8b-5f7768cb90ce)

I've tried a fresh install w/ SteamVR Beta 2.5.2 + OpenVR-Autostarter 0.4.0 and it's working on my side.

Have you tried fully closing (system tray icon) and launching the application while SteamVR is running?

Can you check if there's a file called `dreiekk.OpenVR-Autostarter.vrappconfig` inside your Steam vrappconfig folder?
That's usually located at `C:\Program Files (x86)\Steam\config\vrappconfig`.

**Comment by Adastram1** [comment]
Hello, I have the same problem, I installed everything but when i look in the SteamVR settings windows, the 'OpenVR-Autostarter' doesn't show up. (Picture Below)

![image](https://github.com/user-attachments/assets/8e8f886f-dfe4-4795-948b-f125897d50f8)

Also, there is no dreiekk.OpenVR-Autostarter.vrappconfig file in my steam wrappconfig folder. (Pic Below)
![image](https://github.com/user-attachments/assets/851f13c6-0a4d-4d36-8479-bb0008800a23)

**Comment by Adastram1** [comment]
Here, this should fix your issues #13 .
Have a nice day !
@EchoTheNeko
